name: Frontend CI
on:
  pull_request:
      branches:
      - main
jobs:
  lint:


  test:


  build: ##only runs if both lint and test job have succeeded. I need to build the application using docker
    runs-on: ubuntu-latest ##?????this is debatable. Putting it here as of Wed 04/09 to check if it's actually necessary
    needs: [lint, test]
    steps:
      - name: Checkout code ##first step is to checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ##second step is to setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: latest


        ##missing step on how to Perform a cache action to restore cache before dependency install
        
      - name: Install dependencies ##fourth step is to install dependencies
        run: npm ci

      - name: Run tests ##fifth step is to run tests
        run: npm test

    