name: Frontend CD
on:
  workflow_dispatch:
  push:
    branches:
      -main

env:
  NODE_VERSION: '20.x'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          
      - name: Install Dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        run: cd starter/frontend && npm run lint
  test:
    runs-on: ubuntu-latest

    steps:

  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Logging into ECR
      uses: aws-actions/amazon-ecr-login